### ISSUE TITLE
An option to block in WordPress Edit Post

### ISSUE THREAD

**Issue by wrooot** [Dook1/AutocopySelection2keyboard#1]
Started using this add-on recently. I have only enabled Plain (Selection.ToString) and everything else as off. When i select text in WordPress Edit Post input window it copies the text. Which i don't want. I guess Edit Post is not treated as "Selection in input fields".

**Comment by Dook1** [comment]
Give a link to this wordpress forum.

**Comment by wrooot** [comment]
It's not a forum, but my personal blog and this happens in blog post editor.

**Comment by Dook1** [comment]
I need any example to check

**Comment by wrooot** [comment]
You can try on this demo page https://www.softaculous.com/demos/WordPress
Click on Admin Panel and login with admin/pass, then press +New>Post.

**Comment by Dook1** [comment]
Wordpress has 2 modes of post editing - Visual and Text (2 buttons in the upper right corner). "Visual" is an Iframe (not input field), "Text" is an input field. If you do not need autocopy then switch to Text mode.

**Comment by wrooot** [comment]
Well, i prefer the Visual mode. I guess i'm left with my other request about domain exclusion then.

**Comment by Dook1** [comment]
Sorry, but I prefer not to make an exclusion mode yet.
