### ISSUE TITLE
WordPress Visial editor still gets copied with excluded domain

### ISSUE THREAD

**Issue by wrooot** [Dook1/AutocopySelection2keyboard#10]
I have enabled exclusion for my domain and it doesn't copy when i browse my blog, but when i edit a post in WordPress Visual editor it still copies text on selection.

This is related to https://github.com/Dook1/AutocopySelection2keyboard/issues/1
I guess filtering by domain is not working with iframes?

**Comment by Dook1** [comment]
"Frame are filtered by document url" checked?
What version of the addon?
I verifed on the demo account - all work.

**Comment by wrooot** [comment]
3.1.1. Frames are filtered by document url is checked.
That demo page is using Blocks editor, which does work correctly. But i'm using older Classic editor. Demo page doesn't allow installing plugins.
maybe you can test this here https://wpjobboard.net/demo/
You can go to Jobs, Add new, it seems to use the classic editor there and it doesn't block auto copy if i add https://demo.wpjobboard.net as exclusion.

**Comment by Dook1** [comment]
Fixed in 3.1.3

**Comment by wrooot** [comment]
Yes, with 3.1.3 it doesn't auto copy. Thanks!
