### ISSUE TITLE
Stops working when copy notifications are off

### ISSUE THREAD

**Issue by ghmv** [Dook1/AutocopySelection2keyboard#11]
Firefox DE 68b10

**Comment by Dook1** [comment]
Checked in 68b10 and in 69a1. Works.

**Comment by ghmv** [comment]
You're right, it doesn't make any change now (I don't know why I saw the difference yesterday).

The problem are HTML copy formats. It cannot be pasted nearly anywhere. It skips a clipboard somehow – if plain text is expected, there's nothing in a clipboard to be pasted (even Autohotkey or PureText don't find anything in the clipboard), yet it pastes html text to e.g. Google Docs.

It worked recently with HTML (execCommandCopy) as I'd like (well, I didn't test if html text and not plain text was pasted where html text was possible).

**Comment by Dook1** [comment]
Verifed. Works with all formats. Try to paste into MS Word.

**Comment by ghmv** [comment]
Hello.
Well, as I wrote it works in Google Docs so it will in MS Word.

But those apps can handle html text – but what about apps that cannot? If
you try paste text into notepad, there's nothing to paste. I don't know how
it works but if you copy with ctrl-c, you can paste html text into
html-capable apps (MS Word) and at the same time you can paste plain text
into plain text apps (notepad). I would expect the extension to work the
same way.

Marek

pá 21. 6. 2019 v 16:47 odesílatel Dook1 <notifications@github.com> napsal:

**Comment by Dook1** [comment]
No. InnerHTML and OuterHTML insert only html format into clipboard. If this does not suit you, use execCommandCopy.

**Comment by ghmv** [comment]
But I'm talking about execCommandCopy. This one doesn't work for me…

pá 21. 6. 2019 v 18:44 odesílatel Dook1 <notifications@github.com> napsal:

**Comment by Dook1** [comment]
HTML(execCommandCopy) - it's native Mozilla copy function. This is equivalent to: Right mouse click->Copy. For questions about its operation, contact Mozilla.

**Comment by ghmv** [comment]
That's sad. :( Mozilla's right mouse copy and ctrl-c work as expected (html
and plain text copy both together according to a target app). But your
HTML(execCommandCopy) doesn't. Only Plain(execCommandCopy) works. I don't
know what I can do with it. Tested also in Firefox Nightly (where
AutocopySelection2Clipboard was the only extension).
Marek

pá 21. 6. 2019 v 18:57 odesílatel Dook1 <notifications@github.com> napsal:

**Comment by Dook1** [comment]
This is due postprocessing. Uncheck "Delete empty lines", "Trim outer spaces", "Copy templates"

**Comment by ghmv** [comment]
Right! It was Trim outer spaces.
Thank you much!
Marek

so 22. 6. 2019 v 2:16 odesílatel Dook1 <notifications@github.com> napsal:
