### ISSUE TITLE
[Feature Request] Copy when Delay+Mouse click

### ISSUE THREAD

**Issue by hungrysnake** [Dook1/AutocopySelection2keyboard#12]
Hi, wonderful extension. Thank You

just a quick suggestion here. some time I want to replace a some text in the input box and ended up got copied.

may I suggest adding an option to slightly change the copied behavior
when the text is selected, the copy action get triggered only if the delay timer is up and mouse click is pressed down. In other word, if the text is selected but the mouse button is not on click state, don't copied.

With that I can select the text, release my mouse click, think what I want to edit, then enter the content I want to replace the selected text.

my current delay setting is 800ms

**Comment by Dook1** [comment]
I see no point in this. Declined.
