### ISSUE TITLE
CopyProtectionBreak breaks clicking on Google search fields history

### ISSUE THREAD

**Issue by H48** [Dook1/AutocopySelection2keyboard#13]
Hi,
Firefox v75.0 x64 on Windows 10 v1903 x64, AutocopySelection2Clipboard v3.4.2.

1. Enable CopyProtectionBreak.
2. Go to https://www.google.com/maps/.
3. Type some letters city name into the search field in the upper left, e.g. `Copen`.
4. A list of suggestions appears below the search window.
5. Click on any of them, e.g. `Copenhagen Denmark`.

Expected:
The suggestion that you clicked on is recognized, the suggestion list disappears, the search field is replaced with the suggestion string, e.g. `Copenhagen, Denmark` and the map view is moved to the chosen location.

Actual:
The suggestion list disappears. The search field is not updated nor is it the map view moved.

Similar with Gmail search, clicking a suggestion you click from the suggestion list in Gmail's search has no effect (except closing the suggestion list).

Disabling the CopyProtectionBreak setting makes the search suggestions work as expected.

**Comment by Dook1** [comment]
CopyProtectionBreak does not guarantee the correct behavior of the site after its application. You can disable this feature for specific sites or domains through the "Personal site settings"

**Comment by H48** [comment]
> CopyProtectionBreak does not guarantee the correct behavior of the site after its application.

Of course not. I merely reported an issue.

> You can disable this feature for specific sites or domains through the "Personal site settings"

Does that work with wildcards, please? I tried creating a profile with `*google.com*`, `google.com*`, `https://www.google.com/*` but none of those applied to `https://www.google.com/maps/`. A specific URL is difficult to use since the URL changes each time the map view moves.

**Comment by Dook1** [comment]
The left part of the address of any length. Wildcards is not supported. 
Try it:  https://www.google.com/maps

**Comment by H48** [comment]
* `https://www.google.com/`
* `https://mail.google.com/`
work, thank you!
