### ISSUE TITLE
Option to copy URL as well

### ISSUE THREAD

**Issue by KimPatch** [Dook1/AutocopySelection2keyboard#17]
Nice add-on! It would be great to have the option to automatically copy the URL at the same time as the text and paste both at once.

Thanks again

**Comment by Dook1** [comment]
I was planning to remove this function as useless.

**Comment by KimPatch** [comment]
Which function? 
Use cases for copying URL and text selection at once:
– Increases efficiency for all types of researchers gathering research, Journalist newsgathering, and other folks who might want to more efficiently gather information they might want to look back at or share on any topic (efficient appliances, a school report on cheetahs), or gather information for a more complicated social media post than a single source.

**Comment by Dook1** [comment]
Already added in v3.0.0

**Comment by KimPatch** [comment]
Great, thanks! I took a quick look – works well!
