### ISSUE TITLE
shortcut key does not work

### ISSUE THREAD

**Issue by HAMiDY25** [Dook1/AutocopySelection2keyboard#18]
The settings are as follows, but it does not work.

The shortcut does not function. Autocopy is not disabled. The words are still copied automatically.

<details>

![FF92x64Win10x64aut0c0pyselecti0n2cl1pb0ard](https://user-images.githubusercontent.com/19431107/135730383-8ec9b14b-dbb1-4af4-8945-5a378bac1fe1.png)

</details>

But if applied as follows, it works.

<details>

![FF92x64Win10x64M4NGEXTNSHRTC1TS](https://user-images.githubusercontent.com/19431107/135731452-a88f5df1-964a-4c50-967b-79a299f23792.png)
</details>
But Enabled or disabled status does not change in the toolbar icon! 🤔 ⁉

**Comment by Dook1** [comment]
fixed in v5.0
