### ISSUE TITLE
Please fix the const-redeclaration hack

### ISSUE THREAD

**Issue by maxwowpow** [Dook1/AutocopySelection2keyboard#19]
While debugging other projects, the AutocopyExtension always halts the debugger:
![grafik](https://user-images.githubusercontent.com/169885/144757539-07fc7185-60d4-4651-bc0b-0039432204db.png)

Could you please not use the "hack" with const-redeclaration Exception?

**Comment by Dook1** [comment]
Turn off "Double control injection into frame" in the extension options.
