### ISSUE TITLE
Option to exclude domains

### ISSUE THREAD

**Issue by wrooot** [Dook1/AutocopySelection2keyboard#2]
This is related to https://github.com/Dook1/AutocopySelection2keyboard/issues/1 and could work as a workaround if i could disable this add-on for some domains (say for my domain with WordPress). Used to use such feature in older add-on.

**Comment by Dook1** [comment]
Sorry, but I'm not going to make an exclude domains now. Maybe later.

**Comment by daed-alus** [comment]
cause now is later, any new chances for this?

**Comment by Dook1** [comment]
no

**Comment by daed-alus** [comment]
very sad news

**Comment by Dook1** [comment]
Added to 3.0

**Comment by wrooot** [comment]
Not exactly domains, but still nice :) For anyone reading this later, one has to add an exact URL. I had to add http://www.domain.com/site/ for it to work. Just adding www.domain.com won't work.

**Comment by Dook1** [comment]
It was enough - http://www.domain.com . The protocol must be present necessarily. The comparison goes from left to right to minimize impact on the performance.

**Comment by wrooot** [comment]
Yes, you are right. Works with http in the beginning.
