### ISSUE TITLE
Copy protection break default settings break sites (including facebook)

### ISSUE THREAD

**Issue by Buratinator** [Dook1/AutocopySelection2keyboard#21]
With copy protection enabled, I can't log into this site: https://app.fagura.com/login. The login form and other links on the site don't work.

Also, some links in Facebook don't work (e.g. some notifications) with copy protection break enabled with default settings.

I wasn't expecting Facebook to fall under "rare cases".

**Comment by Dook1** [comment]
CopyProtectionBreak should only be enabled on sites that use copy protection. In all other cases this option will only be harmful, so it should be disabled.
