### ISSUE TITLE
auto highlights text on google image

### ISSUE THREAD

**Issue by bottleblue** [Dook1/AutocopySelection2keyboard#23]
The latest version has a strange bug where it auto highlights the text on google images results page.  Do a search on google images. On the results as you scroll down it will highlight any text. 

Can anyone confirm?

**Comment by Dook1** [comment]
I can't confirm. Disable the addon and test without it.

**Comment by bottleblue** [comment]
I already disabled the addon and the behavior stopped so I assumed it was this addon causing the problem. Unless there's another addon working alongside it that causes it.  When I downgrade to ver. 4 the problem is also gone.

**Comment by bottleblue** [comment]
Ok I found the addon that's co-responsible. It's Imagus  https://addons.mozilla.org/en-US/firefox/addon/imagus/

Can you install that and see if you have the same issue? I'll look through its options and see if I can enable/disable something to make it stop. If I can't I might have to stick with ver. 4

**Comment by Dook1** [comment]
For some reason, this addon generates a mousedown event for an unknown purpose. You can disable "Select links" in my extension options so it doesn't react to these events.

**Comment by bottleblue** [comment]
That worked thx. What does Select links do?

**Comment by Dook1** [comment]
Selects link text without the Alt key.

**Comment by bottleblue** [comment]
hmm I can still copy link text without pressing Alt key

**Comment by Dook1** [comment]
Either you have another addon installed that performs this function, or you start selecting the link outside the link itself.

**Comment by bottleblue** [comment]
I'm selecting directly over the link.  Eh whatever it works i'm not gonna argue lol.  thx again for the help.
