### ISSUE TITLE
"Unselect after copy" breaks F3 searching

### ISSUE THREAD

**Issue by FlyveHest** [Dook1/AutocopySelection2keyboard#25]
Just updated to version 5, but have reverted to 4 as setting the "Unselect after copy" setting breaks Firefox built-in search-next when pressing F3.

Reproduce: Enable "Unselect after copy", go to a page, search for something, press F3 to search for next occurence, nothing happens.

Setting works fine in v4.

Note: I use "find as you type" which might have an effect, I haven't tried disabling this.

**Comment by Dook1** [comment]
fixed in 5.0.3
