### ISSUE TITLE
Completely breaks with Google Docs / Sheets

### ISSUE THREAD

**Issue by FlyveHest** [Dook1/AutocopySelection2keyboard#3]
Extension makes Google Docs / Sheets copy/pasting not work at all. (or at least, super wonky)

Having a domain blacklist, as suggested previous, would be a great help.

**Comment by Dook1** [comment]
I checked it in google docs & in google sheets now. Copying/pasting (Ctrl-c/Ctrl-v) works fine. My add-on doesn't affect these operations at all.

**Comment by FlyveHest** [comment]
Well, the other autocopy extension has a blacklist, and specifically mentions Google Docs as being problematic.

And I have to disable your extension to be able to copy from for instance Excel or Notepad++ into a sheet.

**Comment by Dook1** [comment]
I checked copying/pasting from excel/notepad+++ - all works fine. Describe the problem in more detail.

**Comment by FlyveHest** [comment]
1) Open a new Google Sheet
2) Open Excel, fill in a couple of cells, mark them for copy
3) Tab to Sheet, paste .. this works

But, if you click in any cell before pasting, clipboard contains a linebreak instead of the data you just copied. (I'm guessing the extension auto-copies the contents of the cell)

Moving the active cell with arrow keys works as well, you have to click a cell to get the unintended copy action.

Disabling the extension makes everything work as intended.

**Comment by Dook1** [comment]
You have 3 options:
1) use the keyboard to select the destination cell
2) choose the destination cell and only then do copy/paste
3) click on the addon icon in the panel and select "Disable"

**Comment by FlyveHest** [comment]
Very informative and helpful, thanks
