### ISSUE TITLE
Copy only web page text

### ISSUE THREAD

**Issue by nollinvoyd** [Dook1/AutocopySelection2keyboard#4]
Thanks for the useful addon.

I'm wondering if at some time you might create the option to only copy web page text, and not from areas such as search fields and other text input places such as posts.

I often like to copy then and replace/paste over another selected item, but as it stands now, if I want to replace some text, I must first erase it without highlighting it.

Maybe a better description is no copy in editable fields.

Thanks

**Comment by Dook1** [comment]
Uncheck "Selection in input fields".

**Comment by nollinvoyd** [comment]
How could I have overlooked that 100 times?  Thanks!
