### ISSUE TITLE
Selection in input fields bug

### ISSUE THREAD

**Issue by nollinvoyd** [Dook1/AutocopySelection2keyboard#5]
Firefox 62.0b20, Windows 10 pro

I uncheck this option, but it still copies in input fields.

**Comment by Dook1** [comment]
Firefox 63.0b2 - I uncheck this option and it doesn't copy in input fields.

**Comment by nollinvoyd** [comment]
So I must use beta for this extension

**Comment by Dook1** [comment]
The extension works on all versions of Firefox.

**Comment by nollinvoyd** [comment]
I just updated to Fx63 stable release.  This issue I reported is still occurring, as it was occurring before when I was using the beta version.

For whatever reason, it is not happening here in Github as I write, but it is happening elsewhere, in places where I have participated in forum threads for instance, such as the Windows 10 Forums, as well as when composing Gmail messages.

I really appreciated the value of AutocopySelection2keyboard, but it is very inconvenient that it must be disabled when working in the environments I mentioned

thanks

**Comment by Dook1** [comment]
On the addon icon there is an option "Disable". The option to exclude domains is not planned for the next 100 years.

**Comment by nollinvoyd** [comment]
I wasn't asking for an option to exclude domains, only for the addon to operate as described.

Your sarcasm is unnecessary, and it reinforces the fact that my inquiry is legitimate. 

Since your unkind remark indicates you have no interest in fixing the problem or providing a reasonable explanation for its behavior, perhaps you could at least offer the user an explanation on the Mozilla addon page that there will be occasions when the addon needs to be disabled.

Have a nice day.

**Comment by Dook1** [comment]
> my inquiry is legitimate

Did you buy this extension? Any "inquiry" you have is not "legitimate".
> you have no interest in fixing the problem

I already answered - https://github.com/Dook1/AutocopySelection2keyboard/issues/1
> explanation on the Mozilla addon page that there will be occasions when the addon needs to be disabled

Do not worry so much for others. People are smart enough to guess when and what to turn off.


_Hello to the Mozilla team._

**Comment by bottleblue** [comment]
I'm having this problem also on FF 66.0.3 even though "selection in input fields" is unchecked. I don't remember it happening before 66.0.3 or 66.0.2.

**Comment by Dook1** [comment]
It was always on all versions of FF. Iframe is not an input field. Use "Personal site settings"

**Comment by bottleblue** [comment]
It happens in youtube comment text box which I don't remember ever happening before. Oh well it's not a serious problem just a little annoying

**Comment by Dook1** [comment]
fixed in 3.3.0

**Comment by bottleblue** [comment]
thank you!
