### ISSUE TITLE
Content of clipboard is doubled at paste with middle mouse button

### ISSUE THREAD

**Issue by bitstreamout** [Dook1/AutocopySelection2keyboard#6]
Let's take the first word of the subject:

  ContentContent

.. this is strange, isn't it?

**Comment by Dook1** [comment]
No, it's not strange. You need to use one of two options: either middlemouse.paste = true or "Paste on middle click". If you turn them on at the same time, you will get exactly this effect.

**Comment by bitstreamout** [comment]
Thanks a lot, this does fix it (I've chosen to disable "Paste on middle click") ... maybe it would be an option to check for middlemouse.paste or to give a hint in the option page
