### ISSUE TITLE
Paste on middle click in 3.0.1

### ISSUE THREAD

**Issue by bottleblue** [Dook1/AutocopySelection2keyboard#8]
Middle mouse paste function has changed with 3.0.1.  It now functions exactly the same as about:config middlemouse.paste.  Before 3.0.1, if you highlighted text in a text box and press middle click it would replace the highlighted word with the copied text which I liked. Now it doesn't do that anymore it just pastes the word next to the highlighted text.

Also before 3.0.1 I could disable the copy function and still use paste on middle click option. Now if I disable copy function it also disables paste on middle click. I only wanted to use AutocopySelection2keyboard for the middle mouse paste because I'm using another copy text addon and I don't like the middlemouse.paste command. But now I'm forced to use the copy function and paste on middle click is the same as middlemouse.paste (but worse because I can't paste in url or search bar) so it's useless for me.

Can you change paste on middle click to how it worked before?

**Comment by Dook1** [comment]
Changed in 3.0.2
What's the point of using another addon?

**Comment by bottleblue** [comment]
I was using another addon because I didn't like the copy function in AutocopySelection2keyboard for some reason but I forgot what it was.  The main reason I used your addon was for the middle click paste function which I prefer. Now it's gone.... :(

**Comment by Dook1** [comment]
I changed middle click as you requested in 3.0.2. Have you tried 3.0.2?

**Comment by bottleblue** [comment]
oh I didn't know you updated it again I thought I made a mistake in typing 3.0.1. Let me see.

**Comment by bottleblue** [comment]
Yes it works again. Thank you for changing it back. I don't remember why I didn't use the copy function but it seems to work fine so I'll just use this addon for copying.  Thx!

**Comment by bottleblue** [comment]
Is it possible to prevent the autoscrolling from appearing when pasting with middle click in textboxes?

For example the search box on https://www.tfd.com/   

This doesn't happen with middlemouse.paste command.
