### ISSUE TITLE
Prevent autoscrolling when middle click pasting

### ISSUE THREAD

**Issue by bottleblue** [Dook1/AutocopySelection2keyboard#9]
Is it possible to prevent the autoscrolling from appearing when pasting with middle click in textboxes?

For example the search box on https://www.tfd.com/

This doesn't happen with middlemouse.paste command.

**Comment by Dook1** [comment]
I can't reproduce this. I don't see any scrolling on this site in that search box. 
Try: Firefox-Menu-Preferences-General-Use auto scrolling - uncheck

**Comment by bottleblue** [comment]
Yes the issue is having autoscrolling enabled. If it's disabled then of course it won't show. You can't reproduce it when you have autoscrolling enabled? That's strange it's only happening to me. It happens on many sites.

**Comment by Dook1** [comment]
This can be observed if the mouse moves during a middle click. I cannot do anything about it - this is the internal function of Firefox.

**Comment by bottleblue** [comment]
It doesn't happen though when I disable your addon's middle click paste option and use middlemouse.paste in about: config. 

I'm not sure it has anything to do with moving the mouse. I don't move the mouse at all and it still occurs.

**Comment by Dook1** [comment]
Yes. Autoscroll by middle click - it's internal function of Firefox. I can't disable it.

**Comment by bottleblue** [comment]
I see. Oh well, thanks for looking into it.

**Comment by Dook1** [comment]
Try 3.0.3

**Comment by bottleblue** [comment]
I downloaded 3.1.1 and it works perfectly. The autoscroll does not appear anymore when pasting in text boxes. Very nice. Thank you for fixing those issues so quickly!
